# networks:
#   reverse_proxy:
#     external: true

services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
      args:
        - ENV=prod
      # - ./static_files:/web/static_files
    env_file:
      - $CULTURAL_CONFIG_PATH/web
    networks:
      - default
      # - reverse_proxy
    restart: unless-stopped
