version: "3.8"

services:
  web_cultural:
    build:
      context: ./web
      dockerfile: dev.Dockerfile
      args:
        - ENV=development
    volumes:
      - ./web:/web
      # - ./static_files:/web/static_files
    env_file:
      - ./web/.env
    ports:
      - 81:80